# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'password_prompt.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_password_prompt(object):
    def setupUi(self, password_prompt):
        password_prompt.setObjectName("password_prompt")
        password_prompt.resize(282, 188)
        self.label_one = QtWidgets.QLabel(password_prompt)
        self.label_one.setGeometry(QtCore.QRect(20, 10, 241, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_one.setFont(font)
        self.label_one.setAlignment(QtCore.Qt.AlignCenter)
        self.label_one.setObjectName("label_one")
        self.password_field = QtWidgets.QLineEdit(password_prompt)
        self.password_field.setGeometry(QtCore.QRect(30, 70, 221, 20))
        self.password_field.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password_field.setObjectName("password_field")
        self.submit_button = QtWidgets.QPushButton(password_prompt)
        self.submit_button.setGeometry(QtCore.QRect(150, 110, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.submit_button.setFont(font)
        self.submit_button.setObjectName("submit_button")
        self.cancel_button = QtWidgets.QPushButton(password_prompt)
        self.cancel_button.setGeometry(QtCore.QRect(30, 110, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.cancel_button.setFont(font)
        self.cancel_button.setObjectName("cancel_button")

        self.retranslateUi(password_prompt)
        QtCore.QMetaObject.connectSlotsByName(password_prompt)

    def retranslateUi(self, password_prompt):
        _translate = QtCore.QCoreApplication.translate
        password_prompt.setWindowTitle(_translate("password_prompt", "Form"))
        self.label_one.setText(_translate("password_prompt", "Enter Master Password"))
        self.submit_button.setText(_translate("password_prompt", "Submit"))
        self.cancel_button.setText(_translate("password_prompt", "Cancel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    password_prompt = QtWidgets.QWidget()
    ui = Ui_password_prompt()
    ui.setupUi(password_prompt)
    password_prompt.show()
    sys.exit(app.exec_())
